"""
app/models/schemas.py
---------------------
All Pydantic v2 request / response models.
FastAPI uses these for auto-validation and /docs generation.
"""

from pydantic import BaseModel, EmailStr, Field
from typing import Optional, Literal
from datetime import datetime


# ─── Chat ────────────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    session_id: str = Field(..., description="UUID generated by frontend on first load")
    message: str = Field(..., min_length=1, max_length=2000)

    model_config = {"json_schema_extra": {"example": {
        "session_id": "abc-123",
        "message": "What services does Nodus Decoded offer?"
    }}}


class ChatResponse(BaseModel):
    session_id: str
    reply: str
    intent: Literal["general", "lead", "fallback"]
    # SSE streaming path returns chunks — this is the non-streaming fallback
    sources: list[str] = []  # chunk source filenames used in RAG


# ─── Lead capture ────────────────────────────────────────────────────────────

class LeadRequest(BaseModel):
    session_id: str
    name: str = Field(..., min_length=1, max_length=100)
    email: EmailStr
    phone: Optional[str] = Field(None, max_length=20)
    requirement: str = Field(..., min_length=5, max_length=1000,
                            description="Business requirement captured by the bot")

    model_config = {"json_schema_extra": {"example": {
        "session_id": "abc-123",
        "name": "Rahul Sharma",
        "email": "rahul@startup.com",
        "phone": "+91-9876543210",
        "requirement": "Need SEO and a new landing page for my SaaS product"
    }}}


class LeadResponse(BaseModel):
    success: bool
    lead_id: Optional[str] = None
    message: str


# ─── Health check ────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str
    chroma_loaded: bool
    timestamp: datetime