-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.conversation_logs
(
    id integer NOT NULL DEFAULT nextval('conversation_logs_id_seq'::regclass),
    session_id text COLLATE pg_catalog."default" NOT NULL,
    user_msg text COLLATE pg_catalog."default" NOT NULL,
    bot_reply text COLLATE pg_catalog."default" NOT NULL,
    intent text COLLATE pg_catalog."default",
    latency_ms integer,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT conversation_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.leads
(
    id integer NOT NULL DEFAULT nextval('leads_id_seq'::regclass),
    session_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    phone text COLLATE pg_catalog."default",
    requirement text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT leads_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.conversation_logs
    ADD FOREIGN KEY (session_id)
    REFERENCES public.leads (session_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;